### ISSUE TITLE
Issue with loading kernel modules (sh: /usr/sbin/modload: not found)

### ISSUE THREAD

**Issue by pkts-rs** [vmactions/netbsd-vm#11]
I have a project that makes use of TUN/TAP interfaces, so I need to load the `tuntap` kernel module as part of a CI run. It seems that the `modload` command is missing from the NetBSD VM, though--running either `modload tuntap` or `/usr/sbin/modload tuntap` results in a "not found" error.

**Comment by emadellaloggia** [comment]
install this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by pkts-rs** [comment]
Never mind--this was a result of my own inexperience in NetBSD. I needed to use `/sbin/modload`, not `/usr/sbin/modload`.
