### ISSUE TITLE
error appending to ${GITHUB_ENV}

### ISSUE THREAD

**Issue by schmonz** [vmactions/netbsd-vm#6]
According to GitHub's [Setting an environment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) docs, we can make values available to later workflow steps by appending `key=value` to the file `${GITHUB_ENV}`.

When I do this in netbsd-vm or freebsd-vm (haven't tried others yet), I get an error like so:

`cannot create /home/runner/work/_temp/_runner_file_commands/set_env_a9d4ecc0-d1fe-41b0-9c61-d6e55705d6c5: No such file or directory`

As a workaround, I have this command early in my workflow:

`mkdir -p $(dirname ${GITHUB_ENV})`

But I'm hoping a future vmactions release will take care of this behind the scenes. :-)

**Comment by Neilpang** [comment]
please use the latest release,  it should work now.
